name: Test

on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, macos-11, macos-latest, windows-2019, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
      with:
        go-version: 1.17.x
    - name: Test
      run: go test ./...
